### ISSUE TITLE
"mwapi" is inported but not in dependencies

### ISSUE THREAD

**Issue by Tpt** [mediawiki-utilities/python-mwtext#2]
Thank you for this new library!

I just tried to run it. 

I just ran `pip install mwtext && mwtext preprocess_text -h` and I get the error `ModuleNotFoundError: No module named 'mwapi'` from `mwtext/utilities/preprocess_text.py`.

**Comment by halfak** [comment]
Thanks for the report and the patchset!  Sorry for the delay in closing it.  I'll get a new version up shortly.
